version: '3'
services:
  server:
    image: server:v1
    build: .
    container_name: server
    tty: true

  host:
    image: nginx:latest
    ports:
     - 80:8080
    depends_on:
     - server
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: host
    tty: true